variable "rg_name" {}
variable "location" {}
variable "vnet_cidr_block" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
variable "subnet3_cidr" {}
variable "subnet4_cidr" {}
variable "environment" {}
variable "dns1" {}
variable "dns2" {}
